### ISSUE TITLE
Future ideas list

### ISSUE THREAD

**Issue by tjorim** [K00sKlust/slither.io-bot-manager#4]
## Near future:
- [ ] Clicking on variable value copies the whole value (think a list of scores)
  https://developers.google.com/web/updates/2015/04/cut-and-copy-commands
- [ ] Wrap the content of a table cell if too long

``` css
/* Table layouts by default are `auto`, which overflows
and ignores the `max-width` of the table anyway */
table { table-layout: fixed; }
table td { word-wrap: break-word; }
```
- [x] Ability to paste bot-code directly (if not uploaded online, maybe use a modal)
- [ ] Button to remove a column of the table ~K00sKlust
- [ ] ...
## Far far future:
- [ ] Options menu to specify site-url in which to inject code
- [ ] Export the results to a file ~K00sKlust
